.PHONY: gen-metamodel check-metamodel

YAML   := src/linkml_scala/scala_metamodel.yaml
GEN_PY := src/linkml_scala/scala_metamodel_gen.py

gen-metamodel:
	gen-pydantic $(YAML) > $(GEN_PY).tmp
	@# Prepend header
	printf '# Auto-generated by gen-pydantic from scala_metamodel.yaml — DO NOT EDIT\n' > $(GEN_PY)
	cat $(GEN_PY).tmp >> $(GEN_PY)
	rm -f $(GEN_PY).tmp
	@echo "Generated $(GEN_PY)"

check-metamodel:
	python scripts/check_metamodel_sync.py
